export default {
  login: 'dzajakeks',
  id: 83473422,
  node_id: 'MDQ6VXNlcjgzNDczNDIy',
  avatar_url: 'https://avatars.githubusercontent.com/u/83473422?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/dzajakeks',
  html_url: 'https://github.com/dzajakeks',
  followers_url: 'https://api.github.com/users/dzajakeks/followers',
  following_url:
    'https://api.github.com/users/dzajakeks/following{/other_user}',
  gists_url: 'https://api.github.com/users/dzajakeks/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/dzajakeks/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/dzajakeks/subscriptions',
  organizations_url: 'https://api.github.com/users/dzajakeks/orgs',
  repos_url: 'https://api.github.com/users/dzajakeks/repos',
  events_url: 'https://api.github.com/users/dzajakeks/events{/privacy}',
  received_events_url: 'https://api.github.com/users/dzajakeks/received_events',
  type: 'User',
  site_admin: false,
  name: 'Marko Popovic',
  company: null,
  blog: '',
  location: 'Serbia',
  email: null,
  hireable: null,
  bio: '<Searching For A Job>\r\nA Junior Front-End Developer located in Serbia.',
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: '2021-04-30T19:13:37Z',
  updated_at: '2023-10-18T16:44:41Z',
};
